#!/usr/bin/env bash
# Display information about the domains and subdomains

domains_info () {
    line=$(dig "$2"."$1" | grep -F1 "ANSWER SECTION:" | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
    domains_info "$1" "www"
    domains_info "$1" "lb-01"
    domains_info "$1" "web-01"
    domains_info "$1" "web-02"
elif [ "$#" == 2 ]
then
    domains_info "$1" "$2"
fi