#!/usr/bin/env bash
# redirect
sudo apt-get update
sudo apt-get -y update
sydo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart