#!/usr/bin/env bash
# First advanced exercise
echo $$ > /var/run/holbertonscript.pid

while true
do
    trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT
    echo "To infinity and beyond"
    sleep 2
done