#!/usr/bin/env bash
# First advanced exercise
sudo touch /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid
while true
do echo "To infinity and beyond"
    sleep 2
    trap "echo I hate the kill command; sudo rm -f var/run/holbertonscript.pid; exit" SIGTERM
    trap "echo Y U no love me?!; exit" SIGINT
    trap 'sudo rm -f var/run/holbertonscript.pid; exit' SIGQUIT
done