#!/usr/bin/env bash
# Implements the fizzbuzz exercise
for i in {1..100}
do
    if (( i % 3 == 0 && i % 5 != 0 )); then
        echo "Fizz"
    elif (( i % 3 != 0 && i % 5 == 0 )); then
        echo "Buzz"
    elif (( i % 3 == 0 && i % 5 == 0 )); then
        echo "FizzBuzz"
    else
        echo $i
    fi
done