#!/usr/bin/env bash
# This script implements a nested loop for the clock time
j=0
while ((j <= 12))
do
    echo "Hour: $j"
    i=1
    while ((i < 60))
    do
        echo $i
        ((i += 1))
    done
    ((j += 1))
done
